[pytest]
testpaths =
    tests
    speech_to_text_google/tests
    IllusionCanvasInteractive/tests
python_files = test_*.py
norecursedirs =
    .git
    .venv
    .tools
    .pytest_cache
    __pycache__
