#!/usr/bin/env python3
"""
convert_tiles.py

Prototype PNG/PPM -> GBA 4bpp tile + palette C exporter.

Usage:
  python convert_tiles.py input.png --name placeholder --out assets_placeholder.h

Generates a single C header with two arrays:
  - <name>_tiles (unsigned char[]) : concatenated 4bpp 8x8 tiles (32 bytes each)
  - <name>_palette (unsigned short[]) : 15-bit BGR555 palette entries

This is a prototype tool for the dev workflow; it doesn't handle metatiles or map data.
"""
import argparse
from PIL import Image
import os


def rgb_to_bgr555(r, g, b):
    r5 = (r >> 3) & 0x1F
    g5 = (g >> 3) & 0x1F
    b5 = (b >> 3) & 0x1F
    return (b5 << 10) | (g5 << 5) | r5


def make_tiles(img):
    w, h = img.size
    if w % 8 != 0 or h % 8 != 0:
        raise SystemExit("Image width/height must be multiples of 8")

    px = img.load()
    tiles = []
    for ty in range(0, h, 8):
        for tx in range(0, w, 8):
            tile_bytes = []
            for row in range(8):
                # pack pixels two-per-byte (low nibble first, then high nibble)
                for col in range(0, 8, 2):
                    p0 = px[tx + col, ty + row]
                    p1 = px[tx + col + 1, ty + row]
                    byte = (p1 & 0xF) << 4 | (p0 & 0xF)
                    tile_bytes.append(byte)
            tiles.extend(tile_bytes)
    return tiles


def write_header(out_path, name, tiles, palette):
    arr_name_tiles = f"{name}_tiles"
    arr_name_pal = f"{name}_palette"

    with open(out_path, "w") as f:
        f.write("// Generated by convert_tiles.py - prototype output\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")

        # tiles
        f.write(f"const uint8_t {arr_name_tiles}[] = {{\n")
        hexs = [f"0x{b:02X}" for b in tiles]
        # wrap lines
        for i in range(0, len(hexs), 16):
            line = ", ".join(hexs[i:i+16])
            f.write("    " + line + ",\n")
        f.write("};\n\n")

        # palette
        f.write(f"const uint16_t {arr_name_pal}[] = {{\n")
        pal_hex = [f"0x{p:04X}" for p in palette]
        for i in range(0, len(pal_hex), 8):
            line = ", ".join(pal_hex[i:i+8])
            f.write("    " + line + ",\n")
        f.write("};\n\n")

        f.write(f"const unsigned {arr_name_tiles}_size = {len(tiles)};\n")
        f.write(f"const unsigned {arr_name_pal}_size = {len(palette)};\n")


def main():
    p = argparse.ArgumentParser(description="Export image to GBA 4bpp tiles + palette (prototype)")
    p.add_argument("input", help="Input image (PNG/PPM). Must be multiples of 8.")
    p.add_argument("--name", default="assets", help="Base C identifier name")
    p.add_argument("--out", default=None, help="Output header path (.h)")
    args = p.parse_args()

    im = Image.open(args.input).convert("RGBA")

    # Reduce to 16 colors using adaptive quantization
    pal_im = im.convert("P", palette=Image.ADAPTIVE, colors=16)
    # get palette RGB triplets
    palette_list = pal_im.getpalette()[:16*3]
    rgb_palette = []
    for i in range(0, len(palette_list), 3):
        rgb_palette.append((palette_list[i], palette_list[i+1], palette_list[i+2]))

    # convert to paletted image for indexing
    indexed = pal_im.convert("P")

    # make tiles from indexed image
    tiles = make_tiles(indexed)

    # convert palette to BGR555
    bgr555 = [rgb_to_bgr555(r, g, b) for (r, g, b) in rgb_palette]

    out_path = args.out or (os.path.splitext(args.input)[0] + f"_{args.name}.h")
    write_header(out_path, args.name, tiles, bgr555)
    print(f"Wrote {out_path} - tiles={len(tiles)} bytes palette={len(bgr555)} entries")


if __name__ == '__main__':
    main()
#!/usr/bin/env python3
"""
Simple PNG/PPM -> GBA 4bpp tile exporter (prototype)

Outputs:
- <input>_tiles.bin : raw 8x8 tiles (one byte per pixel, indices 0..15)
- <input>_palette.txt : palette colors (R,G,B 0-31) one per line

Requires Pillow (`pip install pillow`).
"""
import sys
from PIL import Image

def quantize_image(img, colors=16):
    return img.convert('P', palette=Image.ADAPTIVE, colors=colors)

def extract_palette(img):
    palette = img.getpalette()[:48]  # 16 * 3
    cols = []
    for i in range(0, len(palette), 3):
        r = palette[i] >> 3
        g = palette[i+1] >> 3
        b = palette[i+2] >> 3
        cols.append((r,g,b))
    return cols

def write_tiles(img, out_tiles):
    w,h = img.size
    pixels = img.load()
    with open(out_tiles, 'wb') as f:
        for ty in range(0, h, 8):
            for tx in range(0, w, 8):
                for y in range(8):
                    for x in range(8):
                        px = pixels[tx+x, ty+y]
                        f.write(bytes([px & 0xF]))

def main():
    if len(sys.argv) < 2:
        print('Usage: convert_tiles.py input.png')
        return
    inp = sys.argv[1]
    img = Image.open(inp).convert('RGBA')
    q = quantize_image(img, 16)
    pal = extract_palette(q)
    out_tiles = inp + '_tiles.bin'
    out_pal = inp + '_palette.txt'
    write_tiles(q, out_tiles)
    with open(out_pal, 'w') as f:
        for r,g,b in pal:
            f.write(f"{r} {g} {b}\n")
    print('Wrote', out_tiles, 'and', out_pal)

if __name__ == '__main__':
    main()
