#!/usr/bin/env python3
"""Convert PNG sprite-sheets (single-row frames) into GBA tile+palette C headers.

Usage:
  python convert_to_gba.py --src KaijuGaiden/assets/placeholderassets --out build/gba

The script scans PNGs in --src and for each image will:
 - Quantize to 16-color palette (GBA palette limits) or 256-color reduced (GBA mode dependent)
 - Tile the image into 8x8 tiles and emit a simple C header with tile bytes and palette.

This is a pragmatic converter to get started; for production use, prefer `grit` or `rgbgfx` + devkitPro tools.
"""
import os
import sys
from PIL import Image
import argparse

PALETTE_SIZE = 16


def image_to_tiles_and_palette(im: Image.Image, palette_size=PALETTE_SIZE):
    # convert to paletted image with limited colors
    pal = im.convert('P', palette=Image.ADAPTIVE, colors=palette_size)
    pal = pal.convert('RGBA')
    # get palette colors
    quant = im.convert('P', palette=Image.ADAPTIVE, colors=palette_size)
    palette = quant.getpalette()[:palette_size*3]
    colors = [tuple(palette[i:i+3]) + (255,) for i in range(0, len(palette), 3)]
    # tile into 8x8
    w, h = quant.size
    tiles = []
    for ty in range(0, h, 8):
        for tx in range(0, w, 8):
            tile = []
            for y in range(ty, min(ty+8, h)):
                for x in range(tx, min(tx+8, w)):
                    tile.append(quant.getpixel((x,y)))
            # pad to 8x8
            while len(tile) < 64:
                tile.append(0)
            tiles.append(tile)
    return tiles, colors, quant.size


def write_c_header(name, tiles, palette, size, out_dir):
    base = os.path.join(out_dir, name)
    os.makedirs(out_dir, exist_ok=True)
    hname = base + '.h'
    with open(hname, 'w') as f:
        f.write('// Generated by convert_to_gba.py\n')
        f.write(f'// {name} - {size[0]}x{size[1]} - {len(tiles)} tiles\n\n')
        f.write(f'const unsigned char {name}_tiles[] = {{\n')
        for t in tiles:
            f.write('  ' + ','.join(str(v) for v in t) + ',\n')
        f.write('};\n\n')
        f.write(f'const unsigned short {name}_palette[] = {{\n')
        for c in palette:
            r,g,b,a = c
            # convert 8-bit RGB to 5-bit per channel (GBA format BGR555)
            r5 = (r * 31) // 255
            g5 = (g * 31) // 255
            b5 = (b * 31) // 255
            val = (b5 << 10) | (g5 << 5) | r5
            f.write(f'  0x{val:04x},\n')
        f.write('};\n')
    print('Wrote', hname)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--src', required=True)
    p.add_argument('--out', required=True)
    args = p.parse_args()
    src = args.src
    out = args.out
    if not os.path.isdir(src):
        print('Source directory not found:', src)
        sys.exit(1)
    os.makedirs(out, exist_ok=True)
    for fn in sorted(os.listdir(src)):
        if not fn.lower().endswith('.png'):
            continue
        path = os.path.join(src, fn)
        try:
            im = Image.open(path).convert('RGBA')
            tiles, palette, size = image_to_tiles_and_palette(im)
            name = os.path.splitext(fn)[0].replace('-', '_')
            write_c_header(name, tiles, palette, size, out)
        except Exception as e:
            print('Error converting', fn, e)

if __name__ == '__main__':
    main()
