#!/usr/bin/env python3
"""
gb_convert.py — PNG → Game Boy 2bpp tile data converter

Converts any PNG to a C header containing 2bpp Game Boy tile data.
Input PNG is resized to the specified tile grid, quantized to 4 GB shades,
then encoded as 16-bytes-per-tile 2bpp data (standard DMG format).

2bpp tile format per 8×8 tile (16 bytes):
  bytes 0,1  → row 0 (low bitplane, high bitplane)
  bytes 2,3  → row 1
  ...
  bytes 14,15 → row 7

Shade encoding: 0=lightest (white), 1=light grey, 2=dark grey, 3=darkest (black)
  Bit 7 of each byte = leftmost pixel of the row.
  shade = (lo_bit) | (hi_bit << 1)

Usage:
  python gb_convert.py input.png --tiles WxH --name var_name --out output.h [options]

  --tiles WxH   Tile grid size in tiles (e.g. 2x3 = 16×24 px). Required.
  --name NAME   C array variable name. Required.
  --out FILE    Output .h path. Required.
  --center      Crop a centered square from the input before resizing.
                Recommended for 1024×1024 Recraft outputs (subject centered).
  --flat        Output a flat uint8_t[N*16] array instead of uint8_t[N][16].
"""

import argparse
import os
import sys

# --------------------------------------------------------------------------- #
# GB shade palette: luminance values for indices 0-3
# shade 0 = lightest (white=255), shade 3 = darkest (black=0)
# --------------------------------------------------------------------------- #
_SHADE_LUM = [255, 170, 85, 0]


def _nearest_shade(lum: int) -> int:
    """Map 0-255 luminance to GB shade index 0..3."""
    best = 0
    best_d = abs(lum - _SHADE_LUM[0])
    for i in range(1, 4):
        d = abs(lum - _SHADE_LUM[i])
        if d < best_d:
            best_d = d
            best = i
    return best


def image_to_2bpp(img, tile_w: int, tile_h: int):
    """
    Convert a PIL image to a list of tiles.
    Returns list of `tile_w * tile_h` entries, each a list of 16 ints (bytes).
    """
    from PIL import Image as _Image

    pw, ph = tile_w * 8, tile_h * 8
    if img.size != (pw, ph):
        img = img.resize((pw, ph), _Image.LANCZOS)

    grey = img.convert('L')
    px = grey.load()

    tiles = []
    for ty in range(tile_h):
        for tx in range(tile_w):
            tile_bytes = []
            for row in range(8):
                lo = 0
                hi = 0
                for col in range(8):
                    shade = _nearest_shade(px[tx * 8 + col, ty * 8 + row])
                    bit = 7 - col
                    if shade & 1:
                        lo |= (1 << bit)
                    if shade & 2:
                        hi |= (1 << bit)
                tile_bytes.append(lo)
                tile_bytes.append(hi)
            tiles.append(tile_bytes)
    return tiles


def write_header(out_path: str, name: str, tiles, flat: bool = False):
    """Write a C header file with the tile data array."""
    n = len(tiles)
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('/* Generated by gb_convert.py  —  DO NOT EDIT */\n')
        f.write('#pragma once\n')
        f.write('#include <stdint.h>\n\n')

        if flat or n == 1:
            total = n * 16
            f.write(f'static const uint8_t {name}[{total}] = {{\n')
            for i, tile in enumerate(tiles):
                hexs = ', '.join(f'0x{b:02X}' for b in tile)
                comma = ',' if i < n - 1 else ''
                f.write(f'    {hexs}{comma}  /* tile {i} */\n')
            f.write('};\n')
        else:
            f.write(f'static const uint8_t {name}[{n}][16] = {{\n')
            for i, tile in enumerate(tiles):
                hexs = ', '.join(f'0x{b:02X}' for b in tile)
                comma = ',' if i < n - 1 else ''
                f.write(f'    {{ {hexs} }}{comma}  /* tile {i} */\n')
            f.write('};\n')


def main():
    p = argparse.ArgumentParser(
        description='PNG → Game Boy 2bpp tile converter',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument('input', help='Input PNG path (ideally 1024×1024 Recraft output)')
    p.add_argument('--tiles', required=True,
                   help='Tile grid WxH in tiles, e.g. 2x3')
    p.add_argument('--name', required=True,
                   help='C array variable name')
    p.add_argument('--out', required=True,
                   help='Output .h file path')
    p.add_argument('--center', action='store_true',
                   help='Crop a centered square region from the input first')
    p.add_argument('--flat', action='store_true',
                   help='Output flat array instead of [N][16]')
    args = p.parse_args()

    tw_str, th_str = args.tiles.lower().split('x')
    tw, th = int(tw_str), int(th_str)

    from PIL import Image
    img = Image.open(args.input).convert('RGB')

    if args.center:
        w, h = img.size
        s = min(w, h)
        left = (w - s) // 2
        top = (h - s) // 2
        img = img.crop((left, top, left + s, top + s))

    tiles = image_to_2bpp(img, tw, th)
    write_header(args.out, args.name, tiles, flat=args.flat)
    n_tiles = len(tiles)
    print(f'OK  {args.out}  ({n_tiles} tile{"s" if n_tiles != 1 else ""}, '
          f'{tw}x{th} grid, {tw*8}x{th*8} px)')


if __name__ == '__main__':
    main()
